export const productionCodes: 
    [code: string, 
    nameShort: string, 
    nameLong: string | null, 
    unit: string][] = [
    ["sum_produksjons_og_avloesertilskudd", "Sum tilskudd", "Sum produksjons- og avløsertilskudd", "kr"],
    ["p001", "Epler", "Epler, kg", "kg"],
    ["p002", "Pærer", "Pærer, kg", "kg"],
    ["p003", "Plommer", "Plommer, kg", "kg"],
    ["p004", "Moreller", "Moreller, kg", "kg"],
    ["p005", "Kirsebær", "Kirsebær, kg", "kg"],
    ["p006", "Epler og pærer til press", "Epler og pærer til press, kg", "kg"],
    ["p011", "Jordbær", "Jordbær, kg", "kg"],
    ["p012", "Bringebær", "Bringebær, kg", "kg"],
    ["p013", "Solbær", "Solbær, kg", "kg"],
    ["p014", "Rips", "Rips, kg", "kg"],
    ["p016", "Hageblåbær", "Hageblåbær, kg", "kg"],
    ["p021", "Stikkelsbær", "Stikkelsbær, kg", "kg"],
    ["p022", "Industribær", "Industribær. Av det totale antall kg bær", "kg"],
    ["p031", "Tomat", "Tomat, kg", "kg"],
    ["p032", "Slangeagurk", "Slangeagurk, kg", "kg"],
    ["p033", "Salat", "Salat (inkl. salat på friland) av arten Lactuca sativa, stk", "stk"],
    ["p060", "Poteter", "Poteter, kg", "kg"],
    ["p115_vaar","Hester, under 3 år",null,""],
    ["p116_vaar","Hester, 3 år og eldre",null,""],
    ["p119_vaar","Øvrig storfe",null,""],
    ["p120_vaar","Melkekyr",null,""],
    ["p121_vaar","Ammekyr",null,""],
    ["p139_vaar","Melkesau, født i fjor eller tidligere",null,""],
    ["p140_vaar","Melkegeiter",null,""],
    ["p142_vaar","Ammegeiter",null,""],
    ["p144_vaar","Bukker og ungdyr",null,""],
    ["p145_vaar","Søyer, født i fjor eller tidligere.",null,""],
    ["p146_vaar","Værer, født i fjor eller tidligere",null,""],
    ["p154_vaar","Smågriser","Smågriser, under 20 kg eller alder inntil 8 uker",""],
    ["p155_vaar","Avlspurker","Avlspurker som har fått minst ett kull",""],
    ["p156_vaar","Råner","Råner som er satt inn i avl",""],
    ["p157_vaar","Slaktegriser","Slaktegriser, minst 20 kg, og griser påsatt til avlsdyr, 20-50 kg",""],
    ["p158_vaar","Ungpurker bestemt for avl","Ungpurker bestemt for avl, minst 50 kg eller eldre enn 15 uker",""],
    ["p159_vaar","Ungråner bestemt for avl","Ungråner bestemt for avl, minst 50 kg eller eldre enn 15 uker",""],
    ["p161_vaar","Verpehøner","Verpehøner for konsumeggproduksjon, 20 uker og eldre",""],
    ["p162_hoest","Egg (antall)","Antall rugeegg levert til rugeri i søknadsåret",""],
    ["p168_vaar","Avlsdyr av ender, kalkuner og gjess",null,""],
    ["p174_vaar","Ender, kalkuner og gjess for slakt",null,""],
    ["p175_vaar","Livkyllinger, påsatt til verpehøns",null,""],
    ["p176_vaar","Slaktekyllinger, antall på telledato",null,""],
    ["p178_vaar","Hjort, 1 år og eldre",null,""],
    ["p179_vaar","Hjort, under 1 år",null,""],
    ["p180_vaar","Kaniner","Kaniner som brukes i kjøtt- eller ullproduksjon",""],
    ["p183_vaar","Struts",null,""],
    ["p184","Slaktegriser, slaktet i søknadsåret",null,""],
    ["p185_hoest","Livkyllinger, påsatt til verpehøns, livkalkuner, solgt inneværende år",null,""],
    ["p186","Kyllinger, konvensjonelle, slaktet i søknadsåret",null,""],
    ["p187","Ender, slaktet i søknadsåret",null,""],
    ["p188","Kalkuner, slaktet i søknadsåret",null,""],
    ["p189","Gjess, slaktet i søknadsåret",null,""],
    ["p192_vaar","Esel",null,""],
    ["p193_hoest","Hester i pensjon i beitesesongen",null,""],
    ["p194_hoest","Bifolk",null,""],
    ["p196_vaar","Lama",null,""],
    ["p196_hoest","Lama",null,""],
    ["p197_hoest","Alpakka",null,""],
    ["p197_vaar","Alpakka",null,""],
    ["p210","Fulldyrket eng",null,"dekar"],
    ["p211","Overflatedyrket eng",null,"dekar"],
    ["p212","Innmarksbeite",null,"dekar"],
    ["p213","Andre grovfôrvekster til fôr",null,"dekar"],
    ["p223","Grønngjødsling",null,"dekar"],
    ["p230","Poteter",null,"dekar"],
    ["p231","Annet korn og frø som er berettiget tilskudd",null,"dekar"],
    ["p236","Belgvekster til modning",null,"dekar"],
    ["p237","Oljevekster",null,"dekar"],
    ["p238","Rug og rughvete",null,"dekar"],
    ["p239","Korn til krossing",null,"dekar"],
    ["p240","Vårhvete",null,"dekar"],
    ["p242","Bygg",null,"dekar"],
    ["p243","Havre",null,"dekar"],
    ["p245","Belgvekster høstet før modning)",null,"dekar"],
    ["p247","Høsthvete",null,"dekar"],
    ["p264","Grønnsaker på friland",null,"dekar"],
    ["p271","Moreller og kirsebær",null,"dekar"],
    ["p272","Epler",null,"dekar"],
    ["p273","Pærer",null,"dekar"],
    ["p274","Plommer",null,"dekar"],
    ["p280","Jordbær",null,"dekar"],
    ["p282","Andre bærarter",null,"dekar"],
    ["p283","Andre fruktarter",null,"dekar"],
    ["p285","Planteskoleareal og blomsterdyrking på friland",null,"dekar"],
    ["p290","Brakka areal",null,"dekar"],
    ["p292","Fulldyrket og/eller overflatedyrket areal ute av drift",null,"dekar"],
    ["p293","Innmarksbeite, ute av drift",null,"dekar"],
    ["p294","Areal i drift, men ikke berettiget produksjonstilskudd",null,"dekar"],
    ["p410","Melkekyr og ammekyr på utmarksbeite",null,""],
    ["p411","Melkekyr og ammekyr på beite i minst 12/16 uker",null,""],
    ["p420","Øvrige storfe på utmarksbeite",null,""],
    ["p422","Øvrige storfe på beite i minst 12/16 uker",null,""],
    ["p431_sanket_utmarksbeite","Sauer, født i fjor eller tidligere, sanket fra utmarksbeite",null,""],
    ["p431_sluppet_utmarksbeite","Sauer, født i fjor eller tidligere, sluppet på utmarksbeite",null,""],
    ["p432_sanket_utmarksbeite","Lam, født i år, sanket fra utmarksbeite",null,""],
    ["p432_sluppet_utmarksbeite","Lam, født i år, sluppet på utmarksbeite",null,""],
    ["p440","Geiter, voksne og kje, på utmarksbeite",null,""],
    ["p445","Geiter, voksne og kje, på beite i minst 12/16 uker",null,""],
    ["p450","Hester på utmarksbeite",null,""],
    ["p455","Hester på beite i minst 12/16 uker",null,""],
    ["p480","Lama på beite i minst 12/16 uker",null,""],
    ["p481","Alpakka på beite i minst 12/16 uker",null,""],
    ["p486","Hjort på beite i minst 12/16 uker",null,""],
    ["p487","Sauer, født i fjor eller tidligere, på beite i minst 12/16 uker",null,""],
    ["p488","Lam, født i år, på beite i minst 12/16 uker",null,""],
    ["p521","Salg av grovfôr, høy",null,"kr"],
    ["p522","Salg av grovfôr, surfôr",null,"kr"],
    ["p523","Salg av grovför, høyensilasje",null,"kr"],
    ["p720","Kyr av bevaringsverdig rase",null,""],
    ["p721","Okser av bevaringsverdig rase",null,""],
    ["p722","Søyer av bevaringsverdig rase, født i fjor eller tidligere",null,""],
    ["p723","Værer av bevaringsverdig rase, født i fjor eller tidligere",null,""],
    ["p724","Ammegeiter av bevaringsverdig rase",null,""],
    ["p725","Unghester under 3 år av bevaringsverdig rase",null,""],
    ["p801_vaar","Økologiske melkekyr",null,""],
    ["p801_hoest","Økologiske melkekyr",null,""],
    ["p802_vaar","Økologiske ammekyr",null,""],
    ["p802_hoest","Økologiske ammekyr",null,""],
    ["p803_vaar","Økologiske øvrige storfe",null,""],
    ["p803_hoest","Økologiske øvrige storfe",null,""],
    ["p810_vaar","Økologiske melkegeiter",null,""],
    ["p810_hoest","Økologiske melkegeiter",null,""],
    ["p811_vaar","Økologiske ammegeiter",null,""],
    ["p811_hoest","Økologiske ammegeiter",null,""],
    ["p821_vaar","Økologiske sauer født i fjor eller tidligere",null,""],
    ["p821_hoest","Økologiske sauer født i fjor eller tidligere",null,""],
    ["p830_vaar","Økologiske avlsgriser",null,""],
    ["p830_hoest","Økologiske avlsgriser",null,""],
    ["p831","Økologiske slaktegriser, slaktet i søknadsåret",null,""],
    ["p840","Økologiske kyllinger, slaktet i søknadsåret",null,""],
    ["p841_vaar","Økologiske verpehøner",null,""],
    ["p841_hoest","Økologiske verpehøner",null,""],
    ["p855","Korn, økologisk",null,"dekar"],
    ["p861","Poteter, økologisk",null,"dekar"],
    ["p863","Frukt og bær, økologisk",null,"dekar"],
    ["p864","Grønnsaker, økologisk",null,"dekar"],
    ["p870","Grovfôrareal (unntatt innmarksbeite), økologisk",null,"dekar"],
    ["p871","Innmarksbeite, økologisk",null,"dekar"],
    ["p875","Grønngjødsling, økologisk",null,"dekar"],
    ["p876","Areal brakket for å bekjempe ugress",null,"dekar"],
    ["p880","Innmarksbeite i 1. års karens",null,"dekar"],
    ["p881","Grovfôrareal (unntatt innmarksbeite) i 1. års karens",null,"dekar"],
    ["p882","Annet areal i 1. års karens",null,"dekar"],
    ["arealtilskudd","Arealtilskudd",null,"kr"],
    ["tilskudd_til_avloesning_ved_ferie_og_fritid","Tilskudd til avløsning ved ferie og fritid",null,"kr"],
    ["tilskudd_for_dyr_paa_beite","Tilskudd for dyr på beite",null,"kr"],
    ["tilskudd_for_dyr_av_bevaringsverdige_husdyrraser","Tilskudd for dyr av bevaringsverdige husdyrraser",null,"kr"],
    ["distriktstilskudd_for_frukt_baer_veksthusgroensaker","Distriktstilskudd for frukt, bær, veksthusgrønnsaker",null,"kr"],
    ["distriktstilskudd_for_matpotet_i_nord_norge","Distriktstilskudd for matpotet i Nord-Norge",null,"kr"],
    ["husdyrtilskudd","Husdyrtilskudd",null,"kr"],
    ["kulturlandskapstilskudd","Kulturlandskapstilskudd",null,"kr"],
    ["driftstilskudd_til_melkeproduksjon","Driftstilskudd til melkeproduksjon",null,"kr"],
    ["arealtilskudd_til_oekologisk_landbruk","Arealtilskudd til økologisk landbruk",null,"kr"],
    ["tilskudd_til_oekologisk_husdyrproduksjon","Tilskudd til økologisk husdyrproduksjon",null,"kr"],
    ["tilskudd_til_smaa_og_mellomstore_melkebruk","Tilskudd til små og mellomstore melkebruk",null,"kr"],
    ["driftstilskudd_til_spesialisert_storfekjoettproduksjon","Driftstilskudd til spesialisert storfekjøttproduksjon",null,"kr"],
    ["tilskudd_for_dyr_paa_utmarksbeite","Tilskudd for dyr på utmarksbeite",null,"kr"],
    ["bunnfradrag","Bunnfradrag",null,"kr"]
];