// Kode, select-navn, info-beskrivelse, enhet
export const productionCodes = [
    ["sum_produksjons_og_avloesertilskudd", "Sum tilskudd", "Sum produksjons- og avløsertilskudd", "kr"],
    ["p115_vaar","Hester, under 3 år",null,""],
    ["p116_vaar","Hester, 3 år og eldre",null,""],
    ["p119_vaar","Øvrig storfe",null,""],
    ["p120_vaar","Melkekyr",null,""],
    ["p121_vaar","Ammekyr",null,""],
    ["p139_vaar","Melkesau, født i fjor eller tidligere",null,""],
    ["p140_vaar","Melkegeiter",null,""],
    ["p142_vaar","Ammegeiter",null,""],
    ["p144_vaar","Bukker og ungdyr",null,""],
    ["p145_vaar","Søyer, født i fjor eller tidligere.",null,""],
    ["p146_vaar","Værer, født i fjor eller tidligere",null,""],
    ["p154_vaar","Smågriser","Smågriser, under 20 kg eller alder inntil 8 uker",""],
    ["p155_vaar","Avlspurker","Avlspurker som har fått minst ett kull",""],
    ["p156_vaar","Råner","Råner som er satt inn i avl",""],
    ["p157_vaar","Slaktegriser","Slaktegriser, minst 20 kg, og griser påsatt til avlsdyr, 20-50 kg",""],
    ["p158_vaar","Ungpurker bestemt for avl","Ungpurker bestemt for avl, minst 50 kg eller eldre enn 15 uker",""],
    ["p159_vaar","Ungråner bestemt for avl","Ungråner bestemt for avl, minst 50 kg eller eldre enn 15 uker",""],
    ["p161_vaar","Verpehøner","Verpehøner for konsumeggproduksjon, 20 uker og eldre",""],
    ["p162_hoest","Egg (antall)","Antall rugeegg levert til rugeri i søknadsåret",null,""],
    ["p168_vaar","Avlsdyr av ender, kalkuner og gjess",null,""],
    ["p174_vaar","Ender, kalkuner og gjess for slakt",null,""],
    ["p175_vaar","Livkyllinger, påsatt til verpehøns",null,""],
    ["p176_vaar","Slaktekyllinger, antall på telledato",null,""],
    ["p178_vaar","Hjort, 1 år og eldre",null,""],
    ["p179_vaar","Hjort, under 1 år",null,""],
    ["p180_vaar","Kaniner","Kaniner som brukes i kjøtt- eller ullproduksjon",""],
    ["p183_vaar","Struts",null,""],
    ["p184","Slaktegriser, slaktet i søknadsåret",null,""],
    ["p185_hoest","Livkyllinger, påsatt til verpehøns, livkalkuner, solgt inneværende år",null,""],
    ["p186","Kyllinger, konvensjonelle, slaktet i søknadsåret",null,""],
    ["p187","Ender, slaktet i søknadsåret",null,""],
    ["p188","Kalkuner, slaktet i søknadsåret",null,""],
    ["p189","Gjess, slaktet i søknadsåret",null,""],
    ["p192_vaar","Esel",null,""],
    ["p193_hoest","Hester i pensjon i beitesesongen",null,""],
    ["p194_hoest","Bifolk",null,""],
    ["p196_vaar","Lama",null,""],
    ["p197_vaar","Alpakka",null,""],
    ["p210","Fulldyrket eng",null,"dekar"],
    ["p211","Overflatedyrket eng",null,"dekar"],
    ["p212","Innmarksbeite",null,"dekar"],
    ["p213","Andre grovfôrvekster til fôr",null,"dekar"],
    ["p230","Poteter",null,"dekar"],
    ["p231","Annet korn og frø som er berettiget tilskudd",null,"dekar"],
    ["p236","Belgvekster til modning",null,"dekar"],
    ["p237","Oljevekster",null,"dekar"],
    ["p238","Rug og rughvete",null,"dekar"],
    ["p239","Korn til krossing",null,"dekar"],
    ["p240","Vårhvete",null,"dekar"],
    ["p242","Bygg",null,"dekar"],
    ["p243","Havre",null,"dekar"],
    ["p245","Belgvekster høstet før modning)",null,"dekar"],
    ["p247","Høsthvete",null,"dekar"],
    ["p264","Grønnsaker på friland",null,"dekar"],
    ["p271","Moreller og kirsebær",null,"dekar"],
    ["p272","Epler",null,"dekar"],
    ["p273","Pærer",null,"dekar"],
    ["p274","Plommer",null,"dekar"],
    ["p280","Jordbær",null,"dekar"],
    ["p282","Andre bærarter",null,"dekar"],
    ["p283","Andre fruktarter",null,"dekar"],
    ["p285","Planteskoleareal og blomsterdyrking på friland",null,"dekar"],
    ["p290","Brakka areal",null,"dekar"],
    ["p292","Fulldyrket og/eller overflatedyrket areal ute av drift",null,"dekar"],
    ["p293","Innmarksbeite, ute av drift",null,"dekar"],
    ["p720","Kyr av bevaringsverdig rase",null,""],
    ["p721","Okser av bevaringsverdig rase",null,""],
    ["p722","Søyer av bevaringsverdig rase, født i fjor eller tidligere",null,""],
    ["p723","Værer av bevaringsverdig rase, født i fjor eller tidligere",null,""],
    ["p724","Ammegeiter av bevaringsverdig rase",null,""],
    ["p725","Unghester under 3 år av bevaringsverdig rase",null,""],
    ["p801_vaar","Økologiske melkekyr",null,""],
    ["p802_vaar","Økologiske ammekyr",null,""],
    ["p803_vaar","Økologiske øvrige storfe",null,""],
    ["p810_vaar","Økologiske melkegeiter",null,""],
    ["p811_vaar","Økologiske ammegeiter",null,""],
    ["p821_vaar","Økologiske sauer født i fjor eller tidligere",null,""],
    ["p830_vaar","Økologiske avlsgriser",null,""],
    ["p831","Økologiske slaktegriser, slaktet i søknadsåret",null,""],
    ["p840","Økologiske kyllinger, slaktet i søknadsåret",null,""],
    ["p841_vaar","Økologiske verpehøner",null,""],
    ["p855","Korn, økologisk",null,"dekar"],
    ["p861","Poteter, økologisk",null,"dekar"],
    ["p863","Frukt og bær, økologisk",null,"dekar"],
    ["p864","Grønnsaker, økologisk",null,"dekar"],
]